### ISSUE TITLE
Get rid of the e-waste (scanners and other rubbish)

### ISSUE THREAD

**Issue by jmacarthur** [HACManchester/Space#13]
16:28 < parag0n> just got a text back from waste guy
16:29 < parag0n> he says tape a white bag to each of the scanner part boxes and 
                 put them out as usual
16:29 < srimech> Nice.
16:30 < wlll> \o/
16:31 < srimech> Any limit on box size?
16:31 < parag0n> i said they were around 2ft x 2ft
16:31 < parag0n> so i'd say thats probably the maximum

**Comment by thinkl33t** [comment]
Depends on #14, as we only have one white bag left.

**Comment by thinkl33t** [comment]
A few boxes of these are gone, though we have generated more since!
