### ISSUE TITLE
Labeller is out of Labels

### ISSUE THREAD

**Issue by thinkl33t** [HACManchester/Space#2]
We need more labels for the labeller.  Find out what model it is and order more.

**Comment by thinkl33t** [comment]
I'm willing to buy the labels if someone can find the model number :)

**Comment by BinaryKitten** [comment]
Details from the back of it.

Brother PT-1090

TZ Tape 9/64 - 1/2"  3.5 - 12mm

**Comment by thinkl33t** [comment]
Ordered 2 Carts - http://cgi.ebay.co.uk/ws/eBayISAPI.dll?ViewItem&item=261283878741.

Should be delivered sometime this week.

**Comment by thinkl33t** [comment]
2 packs bought and arrived, in the stationary drawer
