### ISSUE TITLE
Install alfredv2 board on inner door

### ISSUE THREAD

**Issue by thinkl33t** [HACManchester/Space#28]
We have an alfredv2 board built that we are using for coding / testing, and a second one mostly built.  These are an improved version of the existing door control board, designed by @bendooks

The second one (once it has the connector fitted) will be fitted to the inner door, and control access thereof.  

It will also deal with reading the shutter sensor and inner-doorbell, and report if that door is open or closed.

**Comment by BinaryKitten** [comment]
Completed by @thinkl33t 2014-09-20
