### ISSUE TITLE
Get rid of the broken kitchen cupboard and double glazing units.

### ISSUE THREAD

**Issue by thinkl33t** [HACManchester/Space#9]
These take up way too much workshop space and aren't going to actually be used for anything.  They could do with being taken to the tip.

**Comment by jmacarthur** [comment]
The kitchen cupboard is gone. The draining rack is still under the metalwork table in case anyone wants to use it to have another try at the draining cupboard. (If the space doesn't need it, I'll remove that too)

**Comment by thinkl33t** [comment]
Double glazing units are gone too.
